# Generated by Django 3.2.6 on 2022-08-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intent', '0002_intent_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='feature',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.DeleteModel(
            name='FeatureContent',
        ),
    ]
