# Generated by Django 3.2.6 on 2022-08-29 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Intent', '0003_auto_20220821_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAdd', models.IntegerField(default=0)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utterance_intent', to='Intent.intent')),
            ],
        ),
    ]
