# Generated by Django 3.2.6 on 2022-08-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intent', '0004_utterance'),
    ]

    operations = [
        migrations.AddField(
            model_name='utterance',
            name='utterance',
            field=models.TextField(default='', max_length=300),
        ),
    ]
