# Generated by Django 3.2.6 on 2022-09-30 10:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(blank=True, default='', max_length=20)),
                ('intent', models.CharField(blank=True, default='', max_length=20)),
                ('intentslist', models.CharField(blank=True, default='', max_length=300)),
                ('inputTokenize', models.TextField(blank=True, default='', max_length=300)),
                ('matchedEntity', models.TextField(blank=True, default='', max_length=300)),
                ('endTime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('startTime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_user', to='User.user')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_process', to='User.process')),
            ],
        ),
    ]
