# Generated by Django 3.2.6 on 2022-09-30 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_process_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='endTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
