# Generated by Django 3.2.6 on 2022-09-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_process_endtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='message',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='log',
            name='type',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
