# Generated by Django 3.2.6 on 2022-10-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20220930_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='choices',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
