# Generated by Django 3.2.6 on 2022-10-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20221028_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='choices',
        ),
        migrations.AddField(
            model_name='process',
            name='intentscore',
            field=models.IntegerField(default=0),
        ),
    ]
