# Generated by Django 3.2.6 on 2022-10-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20221028_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='process',
            name='intentslist',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
