# Generated by Django 3.2.6 on 2022-08-09 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_user_paramtoask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(blank=True, default='', max_length=20)),
                ('intents', models.CharField(blank=True, default='', max_length=20)),
                ('inputTokenize', models.TextField(blank=True, default='', max_length=300)),
                ('matchedEntity', models.TextField(blank=True, default='', max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='inputTokenize',
        ),
        migrations.RemoveField(
            model_name='user',
            name='intent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='matchedEntity',
        ),
        migrations.RemoveField(
            model_name='user',
            name='paramToAsk',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sentence',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.DeleteModel(
            name='paramToAsked',
        ),
        migrations.AddField(
            model_name='process',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_user', to='User.user'),
        ),
    ]
