# Generated by Django 3.2.6 on 2022-08-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20220809_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='intents',
            new_name='intent',
        ),
        migrations.AddField(
            model_name='process',
            name='intentslist',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
