# Generated by Django 3.2.6 on 2022-08-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_auto_20220809_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='intentslist',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
